### ISSUE TITLE
Platform Doc QSFT, new code

### ISSUE THREAD

**Issue by Yennhi-1986** [OneIdentity/Polypkg#1]

**Comment by Yennhi-1986** [comment]
Admin ơi giúp đỡ cho mình kích hoạt lại tài khoản sóng di động và nhận sim card lại như cũ

**Comment by Yennhi-1986** [comment]
Admin sẽ giúp đỡ kích hoạt tài khoản của mình và nhận lại thẻ SIM như cũ ,xin cảm ơn admin nhiều lắm.

**Comment by 924838** [comment]
Yes
